---
title: "3_2_figure_visualization"
author: "Aspen Coyle"
date: "2024-10-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Figure Creation

This script creates figures for the final paper.

```{r libraries, message=FALSE, warning=FALSE}
# Add all required libraries here
list.of.packages <- c("tidyverse", "lubridate", "beepr", "maps", "sf", "ggmap", "leaflet", "ggthemes", "cowplot", "easystats")
# Get names of all required packages that aren't installed
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[, "Package"])]
# Install all new packages
if(length(new.packages)) install.packages(new.packages)


# Load all required libraries
lapply(list.of.packages, FUN = function(X) {
  do.call("require", list(X))
})


```

# Figure 1: Map showing survey sites

```{r}
# Read in the pot data to get the locations
loc_dat <- read.csv(file = "../output/ADFG_SE_AK_pot_surveys/cleaned_data/pot_data_with_temperature.csv")

# Remove all except Project, Location, Latitude, and Longitude, rename columns to be easier
loc_dat <- loc_dat %>%
  select("Project", "Location", "Latitude.Decimal.Degrees", "Longitude.Decimal.Degrees") %>%
  rename(Latitude = Latitude.Decimal.Degrees, 
         Longitude = Longitude.Decimal.Degrees)

# We've got some weird latitudes and longitudes, let's fix
# Drop all latitudes under 50 and over 60
# Drop all longitudes over -130 and under -150
loc_dat <- loc_dat %>%
  dplyr::filter(Latitude > 50 & Latitude < 60) %>%
  dplyr::filter(Longitude > -150 & Longitude < -130)

# Average lat and long by location
loc_dat <- loc_dat %>%
  group_by(Location, Project) %>%
  summarise(avg_lat = mean(Latitude, na.rm = TRUE),
            avg_long = mean(Longitude, na.rm = TRUE))


# Use data to create a geometry column which has compatible coordinates
map_dat <- loc_dat %>% 
  as.data.frame %>% 
  sf::st_as_sf(coords = c(4, 3))

# Convert this to a file that has the coordinates of each site 
sites_sfc <- st_sfc(map_dat$geometry, crs = 4326)

# Test that it's working and looking good
plot(sites_sfc)

# Define the boundaries of our basemap
southeast <- get_stadiamap(
  bbox = c(left = -138, bottom = 56, right = -132, top = 59),
  zoom = 8,
  maptype = "stamen_terrain_background")

# Create map of southeast
se_map <- ggmap(southeast) +
  geom_point(data = loc_dat,
             aes(x = avg_long, 
                 y = avg_lat,
                 shape = Project),
             size = 3) +
  theme_map() +
  theme(legend.position = "none")

# Define boundaries of our Alaska map
alaska <- get_stadiamap(
  bbox = c(left = -180, bottom = 46, right = -120, top = 73),
  zoom = 5,
  maptype = "stamen_terrain_background")

# Create map of Alaska
ak_map <- ggmap(alaska) +
  theme_map() +
  geom_rect(
    xmin = -138,
    ymin = 56, 
    xmax = -132,
    ymax = 59,
    fill = NA,
    colour = "black",
    linewidth = 0.5) +
  theme(legend.position = "none")

# Put AK map on top of SE map, with border around AK map
full_map <- se_map %>%
  ggdraw () +
  draw_plot(ak_map,
            x = 0.0,
            y = 0.0,
            width = 0.45,
            height = 0.45)

# Save plot
ggsave(filename = "../output/ADFG_SE_AK_pot_surveys/diagnostic_images/survey_location_map.png")
```

### Figure 2: Coefficients of Full Model

```{r}
# Set model filepath
model_filepath <- "../output/ADFG_SE_AK_pot_surveys/models/weighted_models/all_crabs/"

# Read in average model
avg_model <- readRDS(file = paste0(model_filepath, "avg_model.rds"))

# Get basic plot
plot(avg_model)

# Create table of coefficients
coef_tab <- summary(avg_model)$coefmat.full
coef_tab <- as.data.frame(coef_tab)

# Turn rownames into column
coef_tab <- rownames_to_column(coef_tab, var = "variable")

# Remove column header whitespace
colnames(coef_tab) <- str_remove_all(colnames(coef_tab), " ")

# Create graph
coef_tab %>%
  ggplot(aes(x = Estimate, y = variable)) +
  geom_point() + 
  geom_errorbar(aes(xmin = Estimate - AdjustedSE, 
                    xmax = Estimate + AdjustedSE),
                width = 0.3) +
  geom_vline(xintercept=0, linetype = "dotted") +
  scale_y_discrete(labels = c("Intercept", "Black Mat", "Leg Condition", "Carapace Width", "Depth", "Latitude", 'Temperature', 'Sex', 'Shell Condition (Cubic)', 'Shell Condition (Linear)', 'Shell Condition (Quadratic)'))


```

